export function buildChangelogHelp(): string {
  return [
    "**OmegaBot Changelog**",
    "",
    "**3.9.13** (2026-02-12)",
    "• Web API: OAuth, auth, posts/comments, events, SSE, weekly/server leaderboards",
    "• /event command: create, update, join, list, results",
    "• /fun utility leaderboard: scope All time / This week / This server",
    "• Help topic: Events; CORS & rate limiting on web API; turn DMs for Connect 4 & Tic-Tac-Toe",
    "• Reminders under /fun utility (remind_set, remind_list, etc.); dead code removed",
    "• Slots: rare random events (Lucky Spin, Double XP, etc.) show in result; error logging uses requestId everywhere",
    "",
    "**3.9.8** (2026-02-26)",
    "• Refactors: daily, stats, achievements, starboard, Connect 4 PvP split into smaller modules",
    "• /fun remind snooze – reschedule a reminder (ID + time); /info server invite – optional 24h invite link",
    "",
    "**3.9.7** (2026-02-12)",
    "• Quote list: limit 5/10/25 (default 25); Quote search: limit option",
    "• Quote context menu: bot messages allowed; autocomplete in DMs: friendly message",
    "• Avatar GIF help note",
    "",
    "**3.9.6** (2026-02-12)",
    "• Help topic: quotes; Quote remove autocomplete",
    "• Quote context menu: embed-only messages; Avatar GIF format",
    "• Suggestion: clearer permission errors",
    "",
    "**3.9.5** (2026-02-12)",
    "• Context menu: right-click message → Quote (saves as server quote)",
    "• Info avatar: size & format options; Suggestion uses modal",
    "• Playback & FAQ: private option / ephemeral by default",
    "",
    "**3.9.4** (2026-02-12)",
    "• Context menu: right-click message → Summarize (DMs summary of messages)",
    "• Rate limit metrics: omegabot_rate_limit_hits_total for cooldown hits",
    "• Ephemeral by default: /profile view & /info user now private unless you choose otherwise",
    "",
    "**3.9.3** (2026-02-12)",
    "• Context menus: right-click user → View Profile, View Achievements",
    "• Admin timeout presets, FAQ tag autocomplete, help topic: summary",
    "",
    "**3.9.2** (2026-02-12)",
    "• Slash commands: Help topic choices (games, profile), giveaway & remind autocomplete",
    "",
    "**3.9.0** (2026-02-12)",
    "• Docker & Docker Compose, web admin dashboard, Grafana dashboard",
    "• Circuit breakers for GitHub/Weather/OpenAI, backup verification",
    "• Dev seed script, hot reload (dev:watch), Dependabot, i18n skeleton",
    "",
    "**3.8.0** (2026-02-12)",
    "• Autocomplete: profile timezone, FAQ keys",
    "• Health & metrics: METRICS_PORT enables /health and /metrics (Prometheus)",
    "• Automated backup: npm run db:backup",
    "• Graceful shutdown, migration system, Discord 429 retry",
    "• Clearer error messages for missing env vars",
    "",
    "**3.7.0** (2026-02-12)",
    "• Interaction handling: defer early, try/catch with fallback, reduces 'interaction failed'",
    "• Autocomplete support for slash commands",
    "• Logs `interactionFailedRecovery: true` when recovering from collector/button errors",
    "",
    "**3.5.0** (2026-02-12)",
    "• `/status vercel` – Check Vercel platform status",
    "• `/status supabase` – Check Supabase platform status",
    "• Uses Statuspage API; shows incidents and degraded components",
    "",
    "**3.3.0** (2026-02-10)",
    "• Hangman: dropdown letters (A–M / N–Z), difficulty, words in SQLite, solve-time stats",
    "• Admin words: HANGMAN_ADMIN_ROLE_ID can add/list words",
    "• New achievement: Speed Demon (solve Hangman in ≤60s)",
    "• Changelog in Discord: /help topic:changelog",
    "",
    "**3.2.0** (2026-02-09)",
    "• Longer game timeouts: 1 hour for Blackjack, Hangman, Wordle, RPS; 10 min per move for Connect 4 & Tic Tac Toe",
    "• **Extend time** button: whoever started the game can add more time",
    "• Timeout reminder: Connect 4 & Tic Tac Toe warn 1 min before move timeout",
    "",
    "**3.1.0** (2026-02-09)",
    "• Rate limiting: slots (3s), blackjack (5s), dice (2s), darts (2s), hangman (10s)",
    "• Daily game metrics & timeout reminders (Connect 4, Tic Tac Toe)",
    "• Retry on API errors; better error handling and logging",
    "",
    "**3.0.0** (2026-01-27)",
    "• New games: Hangman, Wordle, Slots; Blackjack, Connect 4, Would You Rather",
    "• 19 achievements, giveaways, starboard, suggestion system",
    "• 15 slash commands (consolidated from 24)",
    "",
    "Full changelog: GitHub repo → CHANGELOG.md",
  ].join("\n");
}
