export function buildOverviewHelp(args: { isAdmin: boolean }): string {
  const { isAdmin } = args;

  return [
    "**OmegaBot Help**",
    "",
    "**Getting Started**",
    "Type `/` and pick a command from the menu.",
    "Profile, info, and achievements default to private; use `private:false` to show in channel.",
    "Most games support `private` to control visibility.",
    "",
    "**Topics**",
    "Use `/help topic:<topic>` for detailed help:",
    `\`overview\`, \`fun\`, \`games\`, \`profile\`, \`quotes\`, \`notion\`, \`github\`, \`info\`, \`summary\`, \`status\`, \`event\`${isAdmin ? ", `admin`" : ""}, \`commands\`, \`changelog\``,
    "",
    "**Quick Commands**",
    "`/fun daily`       Daily check-in for points",
    "`/fun trivia`      Answer trivia questions",
    "`/fun slots`       Spin the slot machine",
    "`/profile view`    See your stats & achievements",
    "`/levels rank`     See your server XP rank",
    "`/levels leaderboard`  See message XP leaders",
    "`/roles list`      See server roles you can choose",
    "`/info user`       Look up user info",
    "`/wiki`            Search FAQ + Notion wiki",
    "`/achievements`    View unlockable achievements",
    "",
    "**Popular Games**",
    "`/fun blackjack`   Play blackjack",
    "`/fun wordle`      Daily word puzzle",
    "`/fun hangman`     Guess the word",
    "`/fun rps @user`   Challenge to Rock Paper Scissors",
    "",
    "**Events**",
    "`/event create`    Create an event",
    "`/event list`      List events  •  `/event join`  Join an event",
    "",
    "**Server Tools**",
    "Admins can use `/help topic:admin` for automod, warnings, custom commands, self-serve roles, reaction roles, and leveling setup.",
    "",
    "**Web / API**",
    "An optional HTTP API can power a separate website (profiles, leaderboards, events, games). See the project docs: Web platform.",
  ].join("\n");
}
