export function buildAdminHelp(args: { isAdmin: boolean }): string {
  if (!args.isAdmin) {
    return [
      "**Help: Admin**",
      "",
      "You need Manage Server permissions to access admin commands.",
    ].join("\n");
  }

  return [
    "**Help: Admin**",
    "",
    "**Server Configuration**",
    "`/config view`                  View all settings",
    "`/config welcome set`           Set welcome channel",
    "`/config welcome clear`         Clear welcome channel",
    "`/config welcome test`          Send a test welcome message",
    "`/config starboard set`         Set up starboard",
    "`/config starboard clear`       Disable starboard",
    "`/config leveling status`       View message XP settings",
    "`/config leveling role-add`     Add a level reward role",
    "",
    "**Leveling**",
    "`/levels rank`                  View a member's server rank",
    "`/levels leaderboard`           View server XP leaderboard",
    "",
    "**Automod**",
    "`/automod enable`               Enable message filters",
    "`/automod set`                  Toggle invite/link/caps/spam filters",
    "`/automod word-add`             Add a banned word or phrase",
    "`/automod status`               View active filters",
    "",
    "**Warnings**",
    "`/warnings add`                 Warn a member",
    "`/warnings list`                List active warnings",
    "`/warnings clear`               Clear a warning by ID",
    "",
    "**Self-Serve Roles**",
    "`/reaction-roles add`           Map an emoji reaction to a role",
    "`/reaction-roles remove`        Remove a reaction role mapping",
    "`/reaction-roles list`          List reaction roles",
    "",
    "**Custom Commands**",
    "`/custom-commands set`          Create or update a !command",
    "`/custom-commands remove`       Remove a !command",
    "`/custom-commands list`         List custom !commands",
    "",
    "**Knowledge Base**",
    "`/notion status`                Check Notion setup",
    "`/notion templates`             View guided add templates",
    "`/notion create-page`           Create a wiki page",
    "`/notion add`                   Guided Notion page prompt",
    "`/faq add`                      Add a curated FAQ entry",
    "`/faq remove`                   Remove a curated FAQ entry",
    "",
    "**Moderation**",
    "`/admin timeout`    Timeout a user",
    "`/admin kick`       Kick a user",
    "`/admin ban`        Ban a user",
    "",
    "**Other**",
    "`/giveaway start`   Create a giveaway",
    "`/giveaway end`     End giveaway early",
    "`/suggestion`       Manage suggestions",
  ].join("\n");
}
