export function buildFunHelp(): string {
  return [
    "**Help: Fun Commands**",
    "",
    "All fun commands are under `/fun`. Use `/help topic:games` for game details.",
    "",
    "**Daily & Stats**",
    "`/fun daily`          Check in for points & streaks",
    "`/fun stats`          View all your game stats",
    "`/fun utility leaderboard`  See top players",
    "",
    "**Quotes & Jokes**",
    "`/fun quote add`      Save a memorable quote",
    "`/fun quote random`   Get a random quote",
    "`/fun joke random`    Get a random joke",
    "`/fun joke add`       Add a joke",
    "",
    "**Reminders**",
    "`/fun remind set`     Set a reminder (5m, 1h, 1d)",
    "`/fun remind list`    View pending reminders",
    "`/fun remind snooze`  Reschedule a reminder (ID + time, e.g. 30m, 1h)",
    "`/fun remind cancel`  Cancel a reminder",
    "`/fun remind clear`   Cancel all reminders",
    "",
    "**Utility**",
    "`/fun utility poll`        Create a poll",
    "`/fun utility weather`     Current weather",
    "`/fun utility weather7`    7-day forecast",
    "`/fun utility chat`        Chat with the bot (same thread as DMs/@mentions)",
    '                            Or DM the bot or @mention it to chat. Say "new chat" to reset.',
    "`/fun utility roast`       Playful AI roast (you or a friend)",
    "`/fun utility compliment`  Nice AI compliment (you or a friend)",
    "`/fun utility leaderboard` Top players",
    "`/fun fact`                Random interesting fact",
  ].join("\n");
}
