export function buildGamesHelp(): string {
  return [
    "**Help: Games**",
    "",
    "OmegaBot has 14 games! Most track stats and have achievements.",
    "",
    "**Solo Games**",
    "`/fun 8ball`          Ask the magic 8-ball",
    "`/fun trivia`         Trivia with points & streaks",
    "`/fun blackjack`      Blackjack vs dealer",
    "`/fun hangman play`   Guess the word (dropdown letters, pick difficulty)",
    "`/fun wordle`         Daily word puzzle",
    "`/fun slots`          Slot machine (jackpots!)",
    "`/fun darts`          Throw 3 darts (solo or PvP)",
    "`/fun coinflip`       Heads or tails",
    "`/fun dice`           Roll dice",
    "",
    "**PvP Games**",
    "`/fun rps opponent:@user`       Rock Paper Scissors",
    "`/fun tictactoe opponent:@user` Tic Tac Toe",
    "`/fun connect4 user:@user`      Connect 4",
    "`/fun darts opponent:@user`     Darts",
    "",
    "**Other**",
    "`/fun would-you-rather`   Vote on WYR questions",
    "",
    "**View Stats**",
    "Most games support `stats:true` to see your record.",
    "Example: `/fun blackjack stats:true`",
  ].join("\n");
}
