export function buildFunHelp(): string {
  return [
    "**Help: Fun Commands**",
    "",
    "All fun commands are under `/fun`. Use `/help topic:games` for game details.",
    "",
    "**Daily & Stats**",
    "`/fun daily`          Check in for points & streaks",
    "`/fun stats`          View all your game stats",
    "`/fun leaderboard`    See top players",
    "",
    "**Quotes & Jokes**",
    "`/fun quote add`      Save a memorable quote",
    "`/fun quote random`   Get a random quote",
    "`/fun joke random`    Get a random joke",
    "`/fun joke add`       Add a joke",
    "",
    "**Reminders**",
    "`/fun remind set`     Set a reminder (5m, 1h, 1d)",
    "`/fun remind list`    View pending reminders",
    "`/fun remind cancel`  Cancel a reminder",
    "",
    "**Utility**",
    "`/fun weather`        Current weather",
    "`/fun weather7`       7-day forecast",
    "`/fun fact`           Random interesting fact",
    "`/fun poll`           Create a poll",
  ].join("\n");
}
